server:
  port: 8000
  error:
    include-message: always

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
          - AuthenticationFilter 
            
        - id: swiggy
          uri: lb://SWIGGY-SERVICE
          predicates:
            - Path=/api/swiggy/**
          filters:
          - AuthenticationFilter 
            
        - id: restaurant
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurant/**
          filters:
          - AuthenticationFilter
            
        - id: identity
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/iam/api/**
          filters:
          - AuthenticationFilter
            
        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
          filters:
          - AuthenticationFilter